export const LOAD_HAIKUS_SUCCESS = 'LOAD_HAIKUS_SUCCESS';
export const CREATE_HAIKU_SUCCESS = 'CREATE_HAIKU_SUCCESS';
export const DELETE_HAIKU_SUCCESS = 'DELETE_HAIKU_SUCCESS';

export const NEXT_HAIKU = 'NEXT_HAIKU';

export const LOAD_MODAL = 'LOAD_MODAL';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';